sudo: required
services: 
    - docker

before_install:
    -docker build -t ranajoy27/react-test -f ./client/Dockerfile.dev  ./client

script:
    - docker run -e CI=true ranajoy27/react-test npm test 

after_sucess:
    - docker build -t ranajoy27/multi-client ./client
    - docker build -t ranajoy27/multi-nginx ./nginx
    - docker build -t ranajoy27/multi-server ./server
    - docker build -t ranajoy27/multi-worker ./worker
    - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
    - docker push ranajoy27/multi-client
    - docker push ranajoy27/multi-nginx
    - docker push ranajoy27/multi-server
    - docker push ranajoy27/multi-worker




